// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMYMCckn-vI6sZq_ZNp4hq1-sXEfg6W8',
    appId: '1:187938425110:web:e25a490861888aa4cde837',
    messagingSenderId: '187938425110',
    projectId: 'bhandhan-mitra',
    authDomain: 'bhandhan-mitra.firebaseapp.com',
    storageBucket: 'bhandhan-mitra.firebasestorage.app',
    measurementId: 'G-MYCF8RXRKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZEQfM-U63uLBc4TwPXA4p8c1CxV2bI_s',
    appId: '1:187938425110:android:148884fc669dde15cde837',
    messagingSenderId: '187938425110',
    projectId: 'bhandhan-mitra',
    storageBucket: 'bhandhan-mitra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA246Z5dCDrWqxblMOEoM-Yuh3wUotIwRY',
    appId: '1:187938425110:ios:67afb7a74eca8cc6cde837',
    messagingSenderId: '187938425110',
    projectId: 'bhandhan-mitra',
    storageBucket: 'bhandhan-mitra.firebasestorage.app',
    iosBundleId: 'com.example.bandhanmitra',
  );
}
